# Generated by Django 5.1.5 on 2026-01-17 19:09

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customfielddefinition_customfieldinstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "street",
                    models.CharField(help_text="Street address", max_length=255),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Additional street information (apartment, suite, etc.)",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(help_text="City name", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="State or province",
                        max_length=100,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(help_text="Postal or ZIP code", max_length=20),
                ),
                ("country", models.CharField(help_text="Country name", max_length=100)),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "db_table": "core_address",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AlterField(
            model_name="customfieldinstance",
            name="value",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title (Mr., Ms., Dr., etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer's first name",
                        max_length=100,
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer's last name",
                        max_length=100,
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, help_text="Customer's date of birth", null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Customer email address",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer mobile phone number",
                        max_length=50,
                    ),
                ),
                (
                    "landline_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer landline phone number",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about the customer",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the customer is active"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer's address",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="core.address",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "core_customer",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["company", "uuid"],
                        name="core_custom_company_ff63ff_idx",
                    ),
                    models.Index(fields=["email"], name="core_custom_email_899d12_idx"),
                ],
            },
        ),
    ]
