# Generated by Django 5.1.5 on 2026-01-18 12:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_address_alter_customfieldinstance_value_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g., €, $, £)", max_length=10
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Currency code (e.g., EUR, USD, GBP)", max_length=10
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        help_text="Full currency name (e.g., Euro, US Dollar, British Pound)",
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "core_currency",
                "ordering": ["short_name"],
                "unique_together": {
                    ("company", "long_name"),
                    ("company", "short_name"),
                },
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short name for the unit (e.g., h, kg, pcs)",
                        max_length=20,
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        help_text="Long name for the unit (e.g., hours, kilograms, pieces)",
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this unit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "db_table": "core_unit",
                "ordering": ["long_name"],
                "unique_together": {
                    ("company", "long_name"),
                    ("company", "short_name"),
                },
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(help_text="Item name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional item description"
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base/minimum price per unit",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum price per unit (optional). If not set, price_per_unit is the fixed price. Enables flexible pricing for discounts or customer-specific rates.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency for this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.currency",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of measurement for this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "core_item",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price_max__isnull", True),
                            ("price_max__gte", models.F("price_per_unit")),
                            _connector="OR",
                        ),
                        name="item_price_max_gte_price_per_unit",
                    )
                ],
            },
        ),
    ]
