# Generated by Django 5.1.5 on 2026-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_currency_unit_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfielddefinition",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="show_in_ui",
            field=models.BooleanField(default=True),
        ),
    ]
