/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomFieldDefinition,
  CustomFieldMetadata,
  PatchedCustomFieldDefinition,
} from '../models/index';
import {
    CustomFieldDefinitionFromJSON,
    CustomFieldDefinitionToJSON,
    CustomFieldMetadataFromJSON,
    CustomFieldMetadataToJSON,
    PatchedCustomFieldDefinitionFromJSON,
    PatchedCustomFieldDefinitionToJSON,
} from '../models/index';

export interface CustomFieldsCreateRequest {
    customFieldDefinition: Omit<CustomFieldDefinition, 'uuid'|'created_on'|'modified_on'>;
}

export interface CustomFieldsDestroyRequest {
    uuid: string;
}

export interface CustomFieldsPartialUpdateRequest {
    uuid: string;
    patchedCustomFieldDefinition?: Omit<PatchedCustomFieldDefinition, 'uuid'|'created_on'|'modified_on'>;
}

export interface CustomFieldsRetrieveRequest {
    uuid: string;
}

export interface CustomFieldsUpdateRequest {
    uuid: string;
    customFieldDefinition: Omit<CustomFieldDefinition, 'uuid'|'created_on'|'modified_on'>;
}

/**
 * 
 */
export class CustomFieldsApi extends runtime.BaseAPI {

    /**
     */
    async customFieldsCreateRaw(requestParameters: CustomFieldsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldDefinition>> {
        if (requestParameters['customFieldDefinition'] == null) {
            throw new runtime.RequiredError(
                'customFieldDefinition',
                'Required parameter "customFieldDefinition" was null or undefined when calling customFieldsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomFieldDefinitionToJSON(requestParameters['customFieldDefinition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldDefinitionFromJSON(jsonValue));
    }

    /**
     */
    async customFieldsCreate(requestParameters: CustomFieldsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldDefinition> {
        const response = await this.customFieldsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customFieldsDestroyRaw(requestParameters: CustomFieldsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling customFieldsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async customFieldsDestroy(requestParameters: CustomFieldsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.customFieldsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     */
    async customFieldsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CustomFieldDefinition>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CustomFieldDefinitionFromJSON));
    }

    /**
     */
    async customFieldsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CustomFieldDefinition>> {
        const response = await this.customFieldsListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get metadata for client: available model types and data types.
     */
    async customFieldsMetadataRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldMetadata>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/metadata/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldMetadataFromJSON(jsonValue));
    }

    /**
     * Get metadata for client: available model types and data types.
     */
    async customFieldsMetadataRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldMetadata> {
        const response = await this.customFieldsMetadataRetrieveRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async customFieldsPartialUpdateRaw(requestParameters: CustomFieldsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldDefinition>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling customFieldsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedCustomFieldDefinitionToJSON(requestParameters['patchedCustomFieldDefinition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldDefinitionFromJSON(jsonValue));
    }

    /**
     */
    async customFieldsPartialUpdate(requestParameters: CustomFieldsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldDefinition> {
        const response = await this.customFieldsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customFieldsRetrieveRaw(requestParameters: CustomFieldsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldDefinition>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling customFieldsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldDefinitionFromJSON(jsonValue));
    }

    /**
     */
    async customFieldsRetrieve(requestParameters: CustomFieldsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldDefinition> {
        const response = await this.customFieldsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customFieldsUpdateRaw(requestParameters: CustomFieldsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomFieldDefinition>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling customFieldsUpdate().'
            );
        }

        if (requestParameters['customFieldDefinition'] == null) {
            throw new runtime.RequiredError(
                'customFieldDefinition',
                'Required parameter "customFieldDefinition" was null or undefined when calling customFieldsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/custom-fields/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CustomFieldDefinitionToJSON(requestParameters['customFieldDefinition']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomFieldDefinitionFromJSON(jsonValue));
    }

    /**
     */
    async customFieldsUpdate(requestParameters: CustomFieldsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomFieldDefinition> {
        const response = await this.customFieldsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
