/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Item,
  ItemList,
  PatchedItem,
} from '../models/index';
import {
    ItemFromJSON,
    ItemToJSON,
    ItemListFromJSON,
    ItemListToJSON,
    PatchedItemFromJSON,
    PatchedItemToJSON,
} from '../models/index';

export interface ItemsCreateRequest {
    item: Omit<Item, 'uuid'|'currency_details'|'unit_details'|'created_on'|'modified_on'>;
}

export interface ItemsDestroyRequest {
    uuid: string;
}

export interface ItemsListRequest {
    company?: string;
}

export interface ItemsPartialUpdateRequest {
    uuid: string;
    patchedItem?: Omit<PatchedItem, 'uuid'|'currency_details'|'unit_details'|'created_on'|'modified_on'>;
}

export interface ItemsRetrieveRequest {
    uuid: string;
}

export interface ItemsUpdateRequest {
    uuid: string;
    item: Omit<Item, 'uuid'|'currency_details'|'unit_details'|'created_on'|'modified_on'>;
}

/**
 * 
 */
export class ItemsApi extends runtime.BaseAPI {

    /**
     * Create a new item with optional custom fields. Custom fields must be defined for the item model and company before they can be used. The custom_fields object maps field keys to their values.
     */
    async itemsCreateRaw(requestParameters: ItemsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Item>> {
        if (requestParameters['item'] == null) {
            throw new runtime.RequiredError(
                'item',
                'Required parameter "item" was null or undefined when calling itemsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/items/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItemToJSON(requestParameters['item']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemFromJSON(jsonValue));
    }

    /**
     * Create a new item with optional custom fields. Custom fields must be defined for the item model and company before they can be used. The custom_fields object maps field keys to their values.
     */
    async itemsCreate(requestParameters: ItemsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Item> {
        const response = await this.itemsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an item (disabled).
     */
    async itemsDestroyRaw(requestParameters: ItemsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling itemsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/items/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an item (disabled).
     */
    async itemsDestroy(requestParameters: ItemsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.itemsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * List items from companies the user is a member of.
     */
    async itemsListRaw(requestParameters: ItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItemList>>> {
        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/items/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItemListFromJSON));
    }

    /**
     * List items from companies the user is a member of.
     */
    async itemsList(requestParameters: ItemsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItemList>> {
        const response = await this.itemsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Partially update an existing item. You can update custom fields by providing a custom_fields object. Only the custom fields you specify will be updated; others remain unchanged.
     */
    async itemsPartialUpdateRaw(requestParameters: ItemsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Item>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling itemsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/items/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedItemToJSON(requestParameters['patchedItem']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemFromJSON(jsonValue));
    }

    /**
     * Partially update an existing item. You can update custom fields by providing a custom_fields object. Only the custom fields you specify will be updated; others remain unchanged.
     */
    async itemsPartialUpdate(requestParameters: ItemsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Item> {
        const response = await this.itemsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific item by UUID. The response includes all custom field values associated with the item.
     */
    async itemsRetrieveRaw(requestParameters: ItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Item>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling itemsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/items/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific item by UUID. The response includes all custom field values associated with the item.
     */
    async itemsRetrieve(requestParameters: ItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Item> {
        const response = await this.itemsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing item. You can update custom fields by providing a custom_fields object. Only the custom fields you specify will be updated; others remain unchanged.
     */
    async itemsUpdateRaw(requestParameters: ItemsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Item>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling itemsUpdate().'
            );
        }

        if (requestParameters['item'] == null) {
            throw new runtime.RequiredError(
                'item',
                'Required parameter "item" was null or undefined when calling itemsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/items/{uuid}/`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ItemToJSON(requestParameters['item']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemFromJSON(jsonValue));
    }

    /**
     * Update an existing item. You can update custom fields by providing a custom_fields object. Only the custom fields you specify will be updated; others remain unchanged.
     */
    async itemsUpdate(requestParameters: ItemsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Item> {
        const response = await this.itemsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
