/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for the Address model.
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    readonly uuid: string;
    /**
     * Street address
     * @type {string}
     * @memberof Address
     */
    street: string;
    /**
     * Additional street information (apartment, suite, etc.)
     * @type {string}
     * @memberof Address
     */
    street2?: string;
    /**
     * City name
     * @type {string}
     * @memberof Address
     */
    city: string;
    /**
     * State or province
     * @type {string}
     * @memberof Address
     */
    state?: string;
    /**
     * Postal or ZIP code
     * @type {string}
     * @memberof Address
     */
    postalCode: string;
    /**
     * Country name
     * @type {string}
     * @memberof Address
     */
    country: string;
    /**
     * 
     * @type {Date}
     * @memberof Address
     */
    readonly createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof Address
     */
    readonly modifiedOn: Date;
}

/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): value is Address {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('street' in value) || value['street'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('modifiedOn' in value) || value['modifiedOn'] === undefined) return false;
    return true;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'street': json['street'],
        'street2': json['street_2'] == null ? undefined : json['street_2'],
        'city': json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'postalCode': json['postal_code'],
        'country': json['country'],
        'createdOn': (new Date(json['created_on'])),
        'modifiedOn': (new Date(json['modified_on'])),
    };
}

export function AddressToJSON(json: any): Address {
    return AddressToJSONTyped(json, false);
}

export function AddressToJSONTyped(value?: Omit<Address, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'street_2': value['street2'],
        'city': value['city'],
        'state': value['state'],
        'postal_code': value['postalCode'],
        'country': value['country'],
    };
}

