/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for the Currency model.
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    readonly uuid: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    company: string;
    /**
     * Currency symbol (e.g., €, $, £)
     * @type {string}
     * @memberof Currency
     */
    symbol: string;
    /**
     * Currency code (e.g., EUR, USD, GBP)
     * @type {string}
     * @memberof Currency
     */
    shortName: string;
    /**
     * Full currency name (e.g., Euro, US Dollar, British Pound)
     * @type {string}
     * @memberof Currency
     */
    longName: string;
    /**
     * 
     * @type {Date}
     * @memberof Currency
     */
    readonly createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof Currency
     */
    readonly modifiedOn: Date;
}

/**
 * Check if a given object implements the Currency interface.
 */
export function instanceOfCurrency(value: object): value is Currency {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('shortName' in value) || value['shortName'] === undefined) return false;
    if (!('longName' in value) || value['longName'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('modifiedOn' in value) || value['modifiedOn'] === undefined) return false;
    return true;
}

export function CurrencyFromJSON(json: any): Currency {
    return CurrencyFromJSONTyped(json, false);
}

export function CurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Currency {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'company': json['company'],
        'symbol': json['symbol'],
        'shortName': json['short_name'],
        'longName': json['long_name'],
        'createdOn': (new Date(json['created_on'])),
        'modifiedOn': (new Date(json['modified_on'])),
    };
}

export function CurrencyToJSON(json: any): Currency {
    return CurrencyToJSONTyped(json, false);
}

export function CurrencyToJSONTyped(value?: Omit<Currency, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'symbol': value['symbol'],
        'short_name': value['shortName'],
        'long_name': value['longName'],
    };
}

