/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lightweight serializer for customer list views.
 * @export
 * @interface CustomerList
 */
export interface CustomerList {
    /**
     * 
     * @type {string}
     * @memberof CustomerList
     */
    readonly uuid: string;
    /**
     * Title (Mr., Ms., Dr., etc.)
     * @type {string}
     * @memberof CustomerList
     */
    readonly title: string;
    /**
     * Customer's first name
     * @type {string}
     * @memberof CustomerList
     */
    readonly firstname: string;
    /**
     * Customer's last name
     * @type {string}
     * @memberof CustomerList
     */
    readonly lastname: string;
    /**
     * Customer email address
     * @type {string}
     * @memberof CustomerList
     */
    readonly email: string;
    /**
     * Customer mobile phone number
     * @type {string}
     * @memberof CustomerList
     */
    readonly mobilePhone: string;
    /**
     * Customer landline phone number
     * @type {string}
     * @memberof CustomerList
     */
    readonly landlinePhone: string;
    /**
     * Return a brief address summary.
     * @type {string}
     * @memberof CustomerList
     */
    readonly addressSummary: string | null;
    /**
     * Whether the customer is active
     * @type {boolean}
     * @memberof CustomerList
     */
    readonly isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CustomerList
     */
    readonly createdOn: Date;
}

/**
 * Check if a given object implements the CustomerList interface.
 */
export function instanceOfCustomerList(value: object): value is CustomerList {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('mobilePhone' in value) || value['mobilePhone'] === undefined) return false;
    if (!('landlinePhone' in value) || value['landlinePhone'] === undefined) return false;
    if (!('addressSummary' in value) || value['addressSummary'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function CustomerListFromJSON(json: any): CustomerList {
    return CustomerListFromJSONTyped(json, false);
}

export function CustomerListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerList {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'title': json['title'],
        'firstname': json['firstname'],
        'lastname': json['lastname'],
        'email': json['email'],
        'mobilePhone': json['mobile_phone'],
        'landlinePhone': json['landline_phone'],
        'addressSummary': json['address_summary'],
        'isActive': json['is_active'],
        'createdOn': (new Date(json['created_on'])),
    };
}

export function CustomerListToJSON(json: any): CustomerList {
    return CustomerListToJSONTyped(json, false);
}

export function CustomerListToJSONTyped(value?: Omit<CustomerList, 'uuid'|'title'|'firstname'|'lastname'|'email'|'mobile_phone'|'landline_phone'|'address_summary'|'is_active'|'created_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

