/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lightweight serializer for listing items.
 * @export
 * @interface ItemList
 */
export interface ItemList {
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    readonly uuid: string;
    /**
     * Company that owns this item
     * @type {number}
     * @memberof ItemList
     */
    readonly company: number;
    /**
     * Item name
     * @type {string}
     * @memberof ItemList
     */
    name: string;
    /**
     * Base/minimum price per unit
     * @type {string}
     * @memberof ItemList
     */
    pricePerUnit: string;
    /**
     * Maximum price per unit (optional). If not set, price_per_unit is the fixed price. Enables flexible pricing for discounts or customer-specific rates.
     * @type {string}
     * @memberof ItemList
     */
    priceMax?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    readonly currencySymbol: string;
    /**
     * 
     * @type {string}
     * @memberof ItemList
     */
    readonly unitShortName: string;
    /**
     * 
     * @type {Date}
     * @memberof ItemList
     */
    readonly createdOn: Date;
}

/**
 * Check if a given object implements the ItemList interface.
 */
export function instanceOfItemList(value: object): value is ItemList {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('pricePerUnit' in value) || value['pricePerUnit'] === undefined) return false;
    if (!('currencySymbol' in value) || value['currencySymbol'] === undefined) return false;
    if (!('unitShortName' in value) || value['unitShortName'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    return true;
}

export function ItemListFromJSON(json: any): ItemList {
    return ItemListFromJSONTyped(json, false);
}

export function ItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemList {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'company': json['company'],
        'name': json['name'],
        'pricePerUnit': json['price_per_unit'],
        'priceMax': json['price_max'] == null ? undefined : json['price_max'],
        'currencySymbol': json['currency_symbol'],
        'unitShortName': json['unit_short_name'],
        'createdOn': (new Date(json['created_on'])),
    };
}

export function ItemListToJSON(json: any): ItemList {
    return ItemListToJSONTyped(json, false);
}

export function ItemListToJSONTyped(value?: Omit<ItemList, 'uuid'|'company'|'currency_symbol'|'unit_short_name'|'created_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'price_per_unit': value['pricePerUnit'],
        'price_max': value['priceMax'],
    };
}

