/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
    UnitToJSONTyped,
} from './Unit';

/**
 * Serializer for the Item model with nested currency and unit details.
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    readonly uuid: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    company: string;
    /**
     * Item name
     * @type {string}
     * @memberof Item
     */
    name: string;
    /**
     * Optional item description
     * @type {string}
     * @memberof Item
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    currency: string;
    /**
     * 
     * @type {Currency}
     * @memberof Item
     */
    readonly currencyDetails: Currency;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    unit: string;
    /**
     * 
     * @type {Unit}
     * @memberof Item
     */
    readonly unitDetails: Unit;
    /**
     * Base/minimum price per unit
     * @type {string}
     * @memberof Item
     */
    pricePerUnit: string;
    /**
     * Maximum price per unit (optional). If not set, price_per_unit is the fixed price. Enables flexible pricing for discounts or customer-specific rates.
     * @type {string}
     * @memberof Item
     */
    priceMax?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Item
     */
    readonly createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof Item
     */
    readonly modifiedOn: Date;
}

/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('currencyDetails' in value) || value['currencyDetails'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('unitDetails' in value) || value['unitDetails'] === undefined) return false;
    if (!('pricePerUnit' in value) || value['pricePerUnit'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('modifiedOn' in value) || value['modifiedOn'] === undefined) return false;
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'company': json['company'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'currency': json['currency'],
        'currencyDetails': CurrencyFromJSON(json['currency_details']),
        'unit': json['unit'],
        'unitDetails': UnitFromJSON(json['unit_details']),
        'pricePerUnit': json['price_per_unit'],
        'priceMax': json['price_max'] == null ? undefined : json['price_max'],
        'createdOn': (new Date(json['created_on'])),
        'modifiedOn': (new Date(json['modified_on'])),
    };
}

export function ItemToJSON(json: any): Item {
    return ItemToJSONTyped(json, false);
}

export function ItemToJSONTyped(value?: Omit<Item, 'uuid'|'currency_details'|'unit_details'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'name': value['name'],
        'description': value['description'],
        'currency': value['currency'],
        'unit': value['unit'],
        'price_per_unit': value['pricePerUnit'],
        'price_max': value['priceMax'],
    };
}

