/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * Serializer for the Customer model with nested address.
 * @export
 * @interface PatchedCustomer
 */
export interface PatchedCustomer {
    /**
     * 
     * @type {string}
     * @memberof PatchedCustomer
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCustomer
     */
    company?: string;
    /**
     * Title (Mr., Ms., Dr., etc.)
     * @type {string}
     * @memberof PatchedCustomer
     */
    title?: string;
    /**
     * Customer's first name
     * @type {string}
     * @memberof PatchedCustomer
     */
    firstname?: string;
    /**
     * Customer's last name
     * @type {string}
     * @memberof PatchedCustomer
     */
    lastname?: string;
    /**
     * Customer's date of birth
     * @type {Date}
     * @memberof PatchedCustomer
     */
    birthdate?: Date | null;
    /**
     * Customer email address
     * @type {string}
     * @memberof PatchedCustomer
     */
    email?: string;
    /**
     * Customer mobile phone number
     * @type {string}
     * @memberof PatchedCustomer
     */
    mobilePhone?: string;
    /**
     * Customer landline phone number
     * @type {string}
     * @memberof PatchedCustomer
     */
    landlinePhone?: string;
    /**
     * 
     * @type {Address}
     * @memberof PatchedCustomer
     */
    address?: Address | null;
    /**
     * Additional notes about the customer
     * @type {string}
     * @memberof PatchedCustomer
     */
    notes?: string;
    /**
     * Whether the customer is active
     * @type {boolean}
     * @memberof PatchedCustomer
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCustomer
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCustomer
     */
    readonly modifiedOn?: Date;
}

/**
 * Check if a given object implements the PatchedCustomer interface.
 */
export function instanceOfPatchedCustomer(value: object): value is PatchedCustomer {
    return true;
}

export function PatchedCustomerFromJSON(json: any): PatchedCustomer {
    return PatchedCustomerFromJSONTyped(json, false);
}

export function PatchedCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'company': json['company'] == null ? undefined : json['company'],
        'title': json['title'] == null ? undefined : json['title'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'birthdate': json['birthdate'] == null ? undefined : (new Date(json['birthdate'])),
        'email': json['email'] == null ? undefined : json['email'],
        'mobilePhone': json['mobile_phone'] == null ? undefined : json['mobile_phone'],
        'landlinePhone': json['landline_phone'] == null ? undefined : json['landline_phone'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
        'modifiedOn': json['modified_on'] == null ? undefined : (new Date(json['modified_on'])),
    };
}

export function PatchedCustomerToJSON(json: any): PatchedCustomer {
    return PatchedCustomerToJSONTyped(json, false);
}

export function PatchedCustomerToJSONTyped(value?: Omit<PatchedCustomer, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'title': value['title'],
        'firstname': value['firstname'],
        'lastname': value['lastname'],
        'birthdate': value['birthdate'] == null ? undefined : ((value['birthdate'] as any).toISOString().substring(0,10)),
        'email': value['email'],
        'mobile_phone': value['mobilePhone'],
        'landline_phone': value['landlinePhone'],
        'address': AddressToJSON(value['address']),
        'notes': value['notes'],
        'is_active': value['isActive'],
    };
}

