/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for the Currency model.
 * @export
 * @interface PatchedCurrency
 */
export interface PatchedCurrency {
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrency
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrency
     */
    company?: string;
    /**
     * Currency symbol (e.g., €, $, £)
     * @type {string}
     * @memberof PatchedCurrency
     */
    symbol?: string;
    /**
     * Currency code (e.g., EUR, USD, GBP)
     * @type {string}
     * @memberof PatchedCurrency
     */
    shortName?: string;
    /**
     * Full currency name (e.g., Euro, US Dollar, British Pound)
     * @type {string}
     * @memberof PatchedCurrency
     */
    longName?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCurrency
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCurrency
     */
    readonly modifiedOn?: Date;
}

/**
 * Check if a given object implements the PatchedCurrency interface.
 */
export function instanceOfPatchedCurrency(value: object): value is PatchedCurrency {
    return true;
}

export function PatchedCurrencyFromJSON(json: any): PatchedCurrency {
    return PatchedCurrencyFromJSONTyped(json, false);
}

export function PatchedCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'company': json['company'] == null ? undefined : json['company'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'shortName': json['short_name'] == null ? undefined : json['short_name'],
        'longName': json['long_name'] == null ? undefined : json['long_name'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
        'modifiedOn': json['modified_on'] == null ? undefined : (new Date(json['modified_on'])),
    };
}

export function PatchedCurrencyToJSON(json: any): PatchedCurrency {
    return PatchedCurrencyToJSONTyped(json, false);
}

export function PatchedCurrencyToJSONTyped(value?: Omit<PatchedCurrency, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'symbol': value['symbol'],
        'short_name': value['shortName'],
        'long_name': value['longName'],
    };
}

