/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
    UnitToJSONTyped,
} from './Unit';

/**
 * Serializer for the Item model with nested currency and unit details.
 * @export
 * @interface PatchedItem
 */
export interface PatchedItem {
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    company?: string;
    /**
     * Item name
     * @type {string}
     * @memberof PatchedItem
     */
    name?: string;
    /**
     * Optional item description
     * @type {string}
     * @memberof PatchedItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    currency?: string;
    /**
     * 
     * @type {Currency}
     * @memberof PatchedItem
     */
    readonly currencyDetails?: Currency;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    unit?: string;
    /**
     * 
     * @type {Unit}
     * @memberof PatchedItem
     */
    readonly unitDetails?: Unit;
    /**
     * Base/minimum price per unit
     * @type {string}
     * @memberof PatchedItem
     */
    pricePerUnit?: string;
    /**
     * Maximum price per unit (optional). If not set, price_per_unit is the fixed price. Enables flexible pricing for discounts or customer-specific rates.
     * @type {string}
     * @memberof PatchedItem
     */
    priceMax?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedItem
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedItem
     */
    readonly modifiedOn?: Date;
}

/**
 * Check if a given object implements the PatchedItem interface.
 */
export function instanceOfPatchedItem(value: object): value is PatchedItem {
    return true;
}

export function PatchedItemFromJSON(json: any): PatchedItem {
    return PatchedItemFromJSONTyped(json, false);
}

export function PatchedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'company': json['company'] == null ? undefined : json['company'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'currencyDetails': json['currency_details'] == null ? undefined : CurrencyFromJSON(json['currency_details']),
        'unit': json['unit'] == null ? undefined : json['unit'],
        'unitDetails': json['unit_details'] == null ? undefined : UnitFromJSON(json['unit_details']),
        'pricePerUnit': json['price_per_unit'] == null ? undefined : json['price_per_unit'],
        'priceMax': json['price_max'] == null ? undefined : json['price_max'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
        'modifiedOn': json['modified_on'] == null ? undefined : (new Date(json['modified_on'])),
    };
}

export function PatchedItemToJSON(json: any): PatchedItem {
    return PatchedItemToJSONTyped(json, false);
}

export function PatchedItemToJSONTyped(value?: Omit<PatchedItem, 'uuid'|'currency_details'|'unit_details'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'name': value['name'],
        'description': value['description'],
        'currency': value['currency'],
        'unit': value['unit'],
        'price_per_unit': value['pricePerUnit'],
        'price_max': value['priceMax'],
    };
}

