/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUser
 */
export interface PatchedUser {
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    lastName?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     * @type {boolean}
     * @memberof PatchedUser
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    readonly modifiedOn?: Date;
}

/**
 * Check if a given object implements the PatchedUser interface.
 */
export function instanceOfPatchedUser(value: object): value is PatchedUser {
    return true;
}

export function PatchedUserFromJSON(json: any): PatchedUser {
    return PatchedUserFromJSONTyped(json, false);
}

export function PatchedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
        'modifiedOn': json['modified_on'] == null ? undefined : (new Date(json['modified_on'])),
    };
}

export function PatchedUserToJSON(json: any): PatchedUser {
    return PatchedUserToJSONTyped(json, false);
}

export function PatchedUserToJSONTyped(value?: Omit<PatchedUser, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'is_active': value['isActive'],
    };
}

