/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCompany
 */
export interface PatchedCompany {
    /**
     * 
     * @type {string}
     * @memberof PatchedCompany
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCompany
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCompany
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedCompany
     */
    readonly logo?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCompany
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCompany
     */
    readonly modifiedOn?: Date;
}

/**
 * Check if a given object implements the PatchedCompany interface.
 */
export function instanceOfPatchedCompany(value: object): value is PatchedCompany {
    return true;
}

export function PatchedCompanyFromJSON(json: any): PatchedCompany {
    return PatchedCompanyFromJSONTyped(json, false);
}

export function PatchedCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCompany {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
        'modifiedOn': json['modified_on'] == null ? undefined : (new Date(json['modified_on'])),
    };
}

export function PatchedCompanyToJSON(json: any): PatchedCompany {
    return PatchedCompanyToJSONTyped(json, false);
}

export function PatchedCompanyToJSONTyped(value?: Omit<PatchedCompany, 'uuid'|'logo'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

