/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for the Unit model.
 * @export
 * @interface PatchedUnit
 */
export interface PatchedUnit {
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    readonly uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    company?: string;
    /**
     * Short name for the unit (e.g., h, kg, pcs)
     * @type {string}
     * @memberof PatchedUnit
     */
    shortName?: string;
    /**
     * Long name for the unit (e.g., hours, kilograms, pieces)
     * @type {string}
     * @memberof PatchedUnit
     */
    longName?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUnit
     */
    readonly createdOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUnit
     */
    readonly modifiedOn?: Date;
}

/**
 * Check if a given object implements the PatchedUnit interface.
 */
export function instanceOfPatchedUnit(value: object): value is PatchedUnit {
    return true;
}

export function PatchedUnitFromJSON(json: any): PatchedUnit {
    return PatchedUnitFromJSONTyped(json, false);
}

export function PatchedUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUnit {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'company': json['company'] == null ? undefined : json['company'],
        'shortName': json['short_name'] == null ? undefined : json['short_name'],
        'longName': json['long_name'] == null ? undefined : json['long_name'],
        'createdOn': json['created_on'] == null ? undefined : (new Date(json['created_on'])),
        'modifiedOn': json['modified_on'] == null ? undefined : (new Date(json['modified_on'])),
    };
}

export function PatchedUnitToJSON(json: any): PatchedUnit {
    return PatchedUnitToJSONTyped(json, false);
}

export function PatchedUnitToJSONTyped(value?: Omit<PatchedUnit, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'short_name': value['shortName'],
        'long_name': value['longName'],
    };
}

