/* tslint:disable */
/* eslint-disable */
/**
 * Kompello Server API
 * Kompello API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for the Unit model.
 * @export
 * @interface Unit
 */
export interface Unit {
    /**
     * 
     * @type {string}
     * @memberof Unit
     */
    readonly uuid: string;
    /**
     * 
     * @type {string}
     * @memberof Unit
     */
    company: string;
    /**
     * Short name for the unit (e.g., h, kg, pcs)
     * @type {string}
     * @memberof Unit
     */
    shortName: string;
    /**
     * Long name for the unit (e.g., hours, kilograms, pieces)
     * @type {string}
     * @memberof Unit
     */
    longName: string;
    /**
     * 
     * @type {Date}
     * @memberof Unit
     */
    readonly createdOn: Date;
    /**
     * 
     * @type {Date}
     * @memberof Unit
     */
    readonly modifiedOn: Date;
}

/**
 * Check if a given object implements the Unit interface.
 */
export function instanceOfUnit(value: object): value is Unit {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('shortName' in value) || value['shortName'] === undefined) return false;
    if (!('longName' in value) || value['longName'] === undefined) return false;
    if (!('createdOn' in value) || value['createdOn'] === undefined) return false;
    if (!('modifiedOn' in value) || value['modifiedOn'] === undefined) return false;
    return true;
}

export function UnitFromJSON(json: any): Unit {
    return UnitFromJSONTyped(json, false);
}

export function UnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unit {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'company': json['company'],
        'shortName': json['short_name'],
        'longName': json['long_name'],
        'createdOn': (new Date(json['created_on'])),
        'modifiedOn': (new Date(json['modified_on'])),
    };
}

export function UnitToJSON(json: any): Unit {
    return UnitToJSONTyped(json, false);
}

export function UnitToJSONTyped(value?: Omit<Unit, 'uuid'|'created_on'|'modified_on'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'short_name': value['shortName'],
        'long_name': value['longName'],
    };
}

