/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AuthWebauthnAuthenticatePostRequest
 */
export interface AllauthClientV1AuthWebauthnAuthenticatePostRequest {
    /**
     * 
     * @type {object}
     * @memberof AllauthClientV1AuthWebauthnAuthenticatePostRequest
     */
    credential: object;
}

/**
 * Check if a given object implements the AllauthClientV1AuthWebauthnAuthenticatePostRequest interface.
 */
export function instanceOfAllauthClientV1AuthWebauthnAuthenticatePostRequest(value: object): value is AllauthClientV1AuthWebauthnAuthenticatePostRequest {
    if (!('credential' in value) || value['credential'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthWebauthnAuthenticatePostRequestFromJSON(json: any): AllauthClientV1AuthWebauthnAuthenticatePostRequest {
    return AllauthClientV1AuthWebauthnAuthenticatePostRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AuthWebauthnAuthenticatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthWebauthnAuthenticatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'credential': json['credential'],
    };
}

export function AllauthClientV1AuthWebauthnAuthenticatePostRequestToJSON(json: any): AllauthClientV1AuthWebauthnAuthenticatePostRequest {
    return AllauthClientV1AuthWebauthnAuthenticatePostRequestToJSONTyped(json, false);
}

export function AllauthClientV1AuthWebauthnAuthenticatePostRequestToJSONTyped(value?: AllauthClientV1AuthWebauthnAuthenticatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credential': value['credential'],
    };
}

