/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta
 */
export interface AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta {
    /**
     * Whether or not recovery codes where generated automatically.
     * 
     * @type {boolean}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta
     */
    recoveryCodesGenerated?: boolean;
}

/**
 * Check if a given object implements the AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta interface.
 */
export function instanceOfAllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta(value: object): value is AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta {
    return true;
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMetaFromJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta {
    return AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMetaFromJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'recoveryCodesGenerated': json['recovery_codes_generated'] == null ? undefined : json['recovery_codes_generated'],
    };
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMetaToJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta {
    return AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMetaToJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMetaToJSONTyped(value?: AllauthClientV1AccountAuthenticatorsWebauthnPost200ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recovery_codes_generated': value['recoveryCodesGenerated'],
    };
}

