/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AuthEmailVerifyResendPost429Response
 */
export interface AllauthClientV1AuthEmailVerifyResendPost429Response {
    /**
     * 
     * @type {number}
     * @memberof AllauthClientV1AuthEmailVerifyResendPost429Response
     */
    status: AllauthClientV1AuthEmailVerifyResendPost429ResponseStatusEnum;
}


/**
 * @export
 */
export const AllauthClientV1AuthEmailVerifyResendPost429ResponseStatusEnum = {
    NUMBER_429: 429
} as const;
export type AllauthClientV1AuthEmailVerifyResendPost429ResponseStatusEnum = typeof AllauthClientV1AuthEmailVerifyResendPost429ResponseStatusEnum[keyof typeof AllauthClientV1AuthEmailVerifyResendPost429ResponseStatusEnum];


/**
 * Check if a given object implements the AllauthClientV1AuthEmailVerifyResendPost429Response interface.
 */
export function instanceOfAllauthClientV1AuthEmailVerifyResendPost429Response(value: object): value is AllauthClientV1AuthEmailVerifyResendPost429Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthEmailVerifyResendPost429ResponseFromJSON(json: any): AllauthClientV1AuthEmailVerifyResendPost429Response {
    return AllauthClientV1AuthEmailVerifyResendPost429ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthEmailVerifyResendPost429ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthEmailVerifyResendPost429Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function AllauthClientV1AuthEmailVerifyResendPost429ResponseToJSON(json: any): AllauthClientV1AuthEmailVerifyResendPost429Response {
    return AllauthClientV1AuthEmailVerifyResendPost429ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AuthEmailVerifyResendPost429ResponseToJSONTyped(value?: AllauthClientV1AuthEmailVerifyResendPost429Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

