/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest
 */
export interface AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest {
    /**
     * The IDs of the authenticator that are to be deleted.
     * 
     * @type {Array<number>}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest
     */
    authenticators: Array<number>;
}

/**
 * Check if a given object implements the AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest interface.
 */
export function instanceOfAllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest(value: object): value is AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest {
    if (!('authenticators' in value) || value['authenticators'] === undefined) return false;
    return true;
}

export function AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequestFromJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest {
    return AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authenticators': json['authenticators'],
    };
}

export function AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequestToJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest {
    return AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequestToJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequestToJSONTyped(value?: AllauthClientV1AccountAuthenticatorsWebauthnDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authenticators': value['authenticators'],
    };
}

