/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AccountAuthenticatorsWebauthnPutRequest
 */
export interface AllauthClientV1AccountAuthenticatorsWebauthnPutRequest {
    /**
     * Authenticator ID.
     * 
     * @type {number}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnPutRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnPutRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the AllauthClientV1AccountAuthenticatorsWebauthnPutRequest interface.
 */
export function instanceOfAllauthClientV1AccountAuthenticatorsWebauthnPutRequest(value: object): value is AllauthClientV1AccountAuthenticatorsWebauthnPutRequest {
    return true;
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPutRequestFromJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnPutRequest {
    return AllauthClientV1AccountAuthenticatorsWebauthnPutRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountAuthenticatorsWebauthnPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPutRequestToJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnPutRequest {
    return AllauthClientV1AccountAuthenticatorsWebauthnPutRequestToJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPutRequestToJSONTyped(value?: AllauthClientV1AccountAuthenticatorsWebauthnPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

