/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllauthClientV1AuthProviderSignupGet200ResponseData } from './AllauthClientV1AuthProviderSignupGet200ResponseData';
import {
    AllauthClientV1AuthProviderSignupGet200ResponseDataFromJSON,
    AllauthClientV1AuthProviderSignupGet200ResponseDataFromJSONTyped,
    AllauthClientV1AuthProviderSignupGet200ResponseDataToJSON,
    AllauthClientV1AuthProviderSignupGet200ResponseDataToJSONTyped,
} from './AllauthClientV1AuthProviderSignupGet200ResponseData';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';

/**
 * 
 * @export
 * @interface AllauthClientV1AuthProviderSignupGet200Response
 */
export interface AllauthClientV1AuthProviderSignupGet200Response {
    /**
     * 
     * @type {StatusOK}
     * @memberof AllauthClientV1AuthProviderSignupGet200Response
     */
    status: StatusOK;
    /**
     * 
     * @type {AllauthClientV1AuthProviderSignupGet200ResponseData}
     * @memberof AllauthClientV1AuthProviderSignupGet200Response
     */
    data: AllauthClientV1AuthProviderSignupGet200ResponseData;
}



/**
 * Check if a given object implements the AllauthClientV1AuthProviderSignupGet200Response interface.
 */
export function instanceOfAllauthClientV1AuthProviderSignupGet200Response(value: object): value is AllauthClientV1AuthProviderSignupGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthProviderSignupGet200ResponseFromJSON(json: any): AllauthClientV1AuthProviderSignupGet200Response {
    return AllauthClientV1AuthProviderSignupGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthProviderSignupGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthProviderSignupGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
        'data': AllauthClientV1AuthProviderSignupGet200ResponseDataFromJSON(json['data']),
    };
}

export function AllauthClientV1AuthProviderSignupGet200ResponseToJSON(json: any): AllauthClientV1AuthProviderSignupGet200Response {
    return AllauthClientV1AuthProviderSignupGet200ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AuthProviderSignupGet200ResponseToJSONTyped(value?: AllauthClientV1AuthProviderSignupGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
        'data': AllauthClientV1AuthProviderSignupGet200ResponseDataToJSON(value['data']),
    };
}

