/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session';

/**
 * 
 * @export
 * @interface AllauthClientV1AuthSessionsGet200Response
 */
export interface AllauthClientV1AuthSessionsGet200Response {
    /**
     * 
     * @type {StatusOK}
     * @memberof AllauthClientV1AuthSessionsGet200Response
     */
    status: StatusOK;
    /**
     * 
     * @type {Array<Session>}
     * @memberof AllauthClientV1AuthSessionsGet200Response
     */
    data: Array<Session>;
}



/**
 * Check if a given object implements the AllauthClientV1AuthSessionsGet200Response interface.
 */
export function instanceOfAllauthClientV1AuthSessionsGet200Response(value: object): value is AllauthClientV1AuthSessionsGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthSessionsGet200ResponseFromJSON(json: any): AllauthClientV1AuthSessionsGet200Response {
    return AllauthClientV1AuthSessionsGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthSessionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthSessionsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
        'data': ((json['data'] as Array<any>).map(SessionFromJSON)),
    };
}

export function AllauthClientV1AuthSessionsGet200ResponseToJSON(json: any): AllauthClientV1AuthSessionsGet200Response {
    return AllauthClientV1AuthSessionsGet200ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AuthSessionsGet200ResponseToJSONTyped(value?: AllauthClientV1AuthSessionsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
        'data': ((value['data'] as Array<any>).map(SessionToJSON)),
    };
}

