/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { ProviderAccount } from './ProviderAccount';
import {
    ProviderAccountFromJSON,
    ProviderAccountFromJSONTyped,
    ProviderAccountToJSON,
    ProviderAccountToJSONTyped,
} from './ProviderAccount';
import type { EmailAddress } from './EmailAddress';
import {
    EmailAddressFromJSON,
    EmailAddressFromJSONTyped,
    EmailAddressToJSON,
    EmailAddressToJSONTyped,
} from './EmailAddress';

/**
 * 
 * @export
 * @interface AllauthClientV1AuthProviderSignupGet200ResponseData
 */
export interface AllauthClientV1AuthProviderSignupGet200ResponseData {
    /**
     * 
     * @type {Array<EmailAddress>}
     * @memberof AllauthClientV1AuthProviderSignupGet200ResponseData
     */
    email: Array<EmailAddress>;
    /**
     * 
     * @type {ProviderAccount}
     * @memberof AllauthClientV1AuthProviderSignupGet200ResponseData
     */
    account: ProviderAccount;
    /**
     * 
     * @type {User}
     * @memberof AllauthClientV1AuthProviderSignupGet200ResponseData
     */
    user: User;
}

/**
 * Check if a given object implements the AllauthClientV1AuthProviderSignupGet200ResponseData interface.
 */
export function instanceOfAllauthClientV1AuthProviderSignupGet200ResponseData(value: object): value is AllauthClientV1AuthProviderSignupGet200ResponseData {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthProviderSignupGet200ResponseDataFromJSON(json: any): AllauthClientV1AuthProviderSignupGet200ResponseData {
    return AllauthClientV1AuthProviderSignupGet200ResponseDataFromJSONTyped(json, false);
}

export function AllauthClientV1AuthProviderSignupGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthProviderSignupGet200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'email': ((json['email'] as Array<any>).map(EmailAddressFromJSON)),
        'account': ProviderAccountFromJSON(json['account']),
        'user': UserFromJSON(json['user']),
    };
}

export function AllauthClientV1AuthProviderSignupGet200ResponseDataToJSON(json: any): AllauthClientV1AuthProviderSignupGet200ResponseData {
    return AllauthClientV1AuthProviderSignupGet200ResponseDataToJSONTyped(json, false);
}

export function AllauthClientV1AuthProviderSignupGet200ResponseDataToJSONTyped(value?: AllauthClientV1AuthProviderSignupGet200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': ((value['email'] as Array<any>).map(EmailAddressToJSON)),
        'account': ProviderAccountToJSON(value['account']),
        'user': UserToJSON(value['user']),
    };
}

