/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';

/**
 * 
 * @export
 * @interface AllauthClientV1AuthEmailVerifyResendPost200Response
 */
export interface AllauthClientV1AuthEmailVerifyResendPost200Response {
    /**
     * 
     * @type {StatusOK}
     * @memberof AllauthClientV1AuthEmailVerifyResendPost200Response
     */
    status: StatusOK;
}



/**
 * Check if a given object implements the AllauthClientV1AuthEmailVerifyResendPost200Response interface.
 */
export function instanceOfAllauthClientV1AuthEmailVerifyResendPost200Response(value: object): value is AllauthClientV1AuthEmailVerifyResendPost200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthEmailVerifyResendPost200ResponseFromJSON(json: any): AllauthClientV1AuthEmailVerifyResendPost200Response {
    return AllauthClientV1AuthEmailVerifyResendPost200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthEmailVerifyResendPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthEmailVerifyResendPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
    };
}

export function AllauthClientV1AuthEmailVerifyResendPost200ResponseToJSON(json: any): AllauthClientV1AuthEmailVerifyResendPost200Response {
    return AllauthClientV1AuthEmailVerifyResendPost200ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AuthEmailVerifyResendPost200ResponseToJSONTyped(value?: AllauthClientV1AuthEmailVerifyResendPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
    };
}

