/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';
import type { WebAuthnCredentialRequestOptions } from './WebAuthnCredentialRequestOptions';
import {
    WebAuthnCredentialRequestOptionsFromJSON,
    WebAuthnCredentialRequestOptionsFromJSONTyped,
    WebAuthnCredentialRequestOptionsToJSON,
    WebAuthnCredentialRequestOptionsToJSONTyped,
} from './WebAuthnCredentialRequestOptions';

/**
 * 
 * @export
 * @interface AllauthClientV1AuthWebauthnAuthenticateGet200Response
 */
export interface AllauthClientV1AuthWebauthnAuthenticateGet200Response {
    /**
     * 
     * @type {StatusOK}
     * @memberof AllauthClientV1AuthWebauthnAuthenticateGet200Response
     */
    status: StatusOK;
    /**
     * 
     * @type {WebAuthnCredentialRequestOptions}
     * @memberof AllauthClientV1AuthWebauthnAuthenticateGet200Response
     */
    data: WebAuthnCredentialRequestOptions;
}



/**
 * Check if a given object implements the AllauthClientV1AuthWebauthnAuthenticateGet200Response interface.
 */
export function instanceOfAllauthClientV1AuthWebauthnAuthenticateGet200Response(value: object): value is AllauthClientV1AuthWebauthnAuthenticateGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AllauthClientV1AuthWebauthnAuthenticateGet200ResponseFromJSON(json: any): AllauthClientV1AuthWebauthnAuthenticateGet200Response {
    return AllauthClientV1AuthWebauthnAuthenticateGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AuthWebauthnAuthenticateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AuthWebauthnAuthenticateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
        'data': WebAuthnCredentialRequestOptionsFromJSON(json['data']),
    };
}

export function AllauthClientV1AuthWebauthnAuthenticateGet200ResponseToJSON(json: any): AllauthClientV1AuthWebauthnAuthenticateGet200Response {
    return AllauthClientV1AuthWebauthnAuthenticateGet200ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AuthWebauthnAuthenticateGet200ResponseToJSONTyped(value?: AllauthClientV1AuthWebauthnAuthenticateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
        'data': WebAuthnCredentialRequestOptionsToJSON(value['data']),
    };
}

