/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllauthClientV1AccountPhonePostRequest
 */
export interface AllauthClientV1AccountPhonePostRequest {
    /**
     * 
     * @type {string}
     * @memberof AllauthClientV1AccountPhonePostRequest
     */
    phone: string;
}

/**
 * Check if a given object implements the AllauthClientV1AccountPhonePostRequest interface.
 */
export function instanceOfAllauthClientV1AccountPhonePostRequest(value: object): value is AllauthClientV1AccountPhonePostRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function AllauthClientV1AccountPhonePostRequestFromJSON(json: any): AllauthClientV1AccountPhonePostRequest {
    return AllauthClientV1AccountPhonePostRequestFromJSONTyped(json, false);
}

export function AllauthClientV1AccountPhonePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountPhonePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function AllauthClientV1AccountPhonePostRequestToJSON(json: any): AllauthClientV1AccountPhonePostRequest {
    return AllauthClientV1AccountPhonePostRequestToJSONTyped(json, false);
}

export function AllauthClientV1AccountPhonePostRequestToJSONTyped(value?: AllauthClientV1AccountPhonePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

