/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebAuthnCredentialCreationOptions } from './WebAuthnCredentialCreationOptions';
import {
    WebAuthnCredentialCreationOptionsFromJSON,
    WebAuthnCredentialCreationOptionsFromJSONTyped,
    WebAuthnCredentialCreationOptionsToJSON,
    WebAuthnCredentialCreationOptionsToJSONTyped,
} from './WebAuthnCredentialCreationOptions';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';

/**
 * 
 * @export
 * @interface AllauthClientV1AccountAuthenticatorsWebauthnGet200Response
 */
export interface AllauthClientV1AccountAuthenticatorsWebauthnGet200Response {
    /**
     * 
     * @type {StatusOK}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnGet200Response
     */
    status: StatusOK;
    /**
     * 
     * @type {WebAuthnCredentialCreationOptions}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnGet200Response
     */
    data: WebAuthnCredentialCreationOptions;
}



/**
 * Check if a given object implements the AllauthClientV1AccountAuthenticatorsWebauthnGet200Response interface.
 */
export function instanceOfAllauthClientV1AccountAuthenticatorsWebauthnGet200Response(value: object): value is AllauthClientV1AccountAuthenticatorsWebauthnGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AllauthClientV1AccountAuthenticatorsWebauthnGet200ResponseFromJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnGet200Response {
    return AllauthClientV1AccountAuthenticatorsWebauthnGet200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountAuthenticatorsWebauthnGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
        'data': WebAuthnCredentialCreationOptionsFromJSON(json['data']),
    };
}

export function AllauthClientV1AccountAuthenticatorsWebauthnGet200ResponseToJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnGet200Response {
    return AllauthClientV1AccountAuthenticatorsWebauthnGet200ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnGet200ResponseToJSONTyped(value?: AllauthClientV1AccountAuthenticatorsWebauthnGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
        'data': WebAuthnCredentialCreationOptionsToJSON(value['data']),
    };
}

