/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebAuthnAuthenticator } from './WebAuthnAuthenticator';
import {
    WebAuthnAuthenticatorFromJSON,
    WebAuthnAuthenticatorFromJSONTyped,
    WebAuthnAuthenticatorToJSON,
    WebAuthnAuthenticatorToJSONTyped,
} from './WebAuthnAuthenticator';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';

/**
 * 
 * @export
 * @interface AllauthClientV1AccountAuthenticatorsWebauthnPut200Response
 */
export interface AllauthClientV1AccountAuthenticatorsWebauthnPut200Response {
    /**
     * 
     * @type {StatusOK}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnPut200Response
     */
    status: StatusOK;
    /**
     * 
     * @type {WebAuthnAuthenticator}
     * @memberof AllauthClientV1AccountAuthenticatorsWebauthnPut200Response
     */
    data: WebAuthnAuthenticator;
}



/**
 * Check if a given object implements the AllauthClientV1AccountAuthenticatorsWebauthnPut200Response interface.
 */
export function instanceOfAllauthClientV1AccountAuthenticatorsWebauthnPut200Response(value: object): value is AllauthClientV1AccountAuthenticatorsWebauthnPut200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPut200ResponseFromJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnPut200Response {
    return AllauthClientV1AccountAuthenticatorsWebauthnPut200ResponseFromJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllauthClientV1AccountAuthenticatorsWebauthnPut200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
        'data': WebAuthnAuthenticatorFromJSON(json['data']),
    };
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPut200ResponseToJSON(json: any): AllauthClientV1AccountAuthenticatorsWebauthnPut200Response {
    return AllauthClientV1AccountAuthenticatorsWebauthnPut200ResponseToJSONTyped(json, false);
}

export function AllauthClientV1AccountAuthenticatorsWebauthnPut200ResponseToJSONTyped(value?: AllauthClientV1AccountAuthenticatorsWebauthnPut200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
        'data': WebAuthnAuthenticatorToJSON(value['data']),
    };
}

