/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndSessions
 */
export interface EndSessions {
    /**
     * The IDs of the sessions that are to be ended.
     * 
     * @type {Array<number>}
     * @memberof EndSessions
     */
    sessions: Array<number>;
}

/**
 * Check if a given object implements the EndSessions interface.
 */
export function instanceOfEndSessions(value: object): value is EndSessions {
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    return true;
}

export function EndSessionsFromJSON(json: any): EndSessions {
    return EndSessionsFromJSONTyped(json, false);
}

export function EndSessionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndSessions {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': json['sessions'],
    };
}

export function EndSessionsToJSON(json: any): EndSessions {
    return EndSessionsToJSONTyped(json, false);
}

export function EndSessionsToJSONTyped(value?: EndSessions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': value['sessions'],
    };
}

