/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MFATrust
 */
export interface MFATrust {
    /**
     * 
     * @type {boolean}
     * @memberof MFATrust
     */
    trust: boolean;
}

/**
 * Check if a given object implements the MFATrust interface.
 */
export function instanceOfMFATrust(value: object): value is MFATrust {
    if (!('trust' in value) || value['trust'] === undefined) return false;
    return true;
}

export function MFATrustFromJSON(json: any): MFATrust {
    return MFATrustFromJSONTyped(json, false);
}

export function MFATrustFromJSONTyped(json: any, ignoreDiscriminator: boolean): MFATrust {
    if (json == null) {
        return json;
    }
    return {
        
        'trust': json['trust'],
    };
}

export function MFATrustToJSON(json: any): MFATrust {
    return MFATrustToJSONTyped(json, false);
}

export function MFATrustToJSONTyped(value?: MFATrust | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trust': value['trust'],
    };
}

