/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasskeySignup
 */
export interface PasskeySignup {
    /**
     * The email address.
     * 
     * @type {string}
     * @memberof PasskeySignup
     */
    email?: string;
    /**
     * The phone number.
     * 
     * @type {string}
     * @memberof PasskeySignup
     */
    phone?: string;
    /**
     * The username.
     * 
     * @type {string}
     * @memberof PasskeySignup
     */
    username?: string;
}

/**
 * Check if a given object implements the PasskeySignup interface.
 */
export function instanceOfPasskeySignup(value: object): value is PasskeySignup {
    return true;
}

export function PasskeySignupFromJSON(json: any): PasskeySignup {
    return PasskeySignupFromJSONTyped(json, false);
}

export function PasskeySignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasskeySignup {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function PasskeySignupToJSON(json: any): PasskeySignup {
    return PasskeySignupToJSONTyped(json, false);
}

export function PasskeySignupToJSONTyped(value?: PasskeySignup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phone': value['phone'],
        'username': value['username'],
    };
}

