/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusAccepted } from './StatusAccepted';
import {
    StatusAcceptedFromJSON,
    StatusAcceptedFromJSONTyped,
    StatusAcceptedToJSON,
    StatusAcceptedToJSONTyped,
} from './StatusAccepted';
import type { PhoneNumber } from './PhoneNumber';
import {
    PhoneNumberFromJSON,
    PhoneNumberFromJSONTyped,
    PhoneNumberToJSON,
    PhoneNumberToJSONTyped,
} from './PhoneNumber';

/**
 * 
 * @export
 * @interface PhoneNumberChangeResponse
 */
export interface PhoneNumberChangeResponse {
    /**
     * 
     * @type {StatusAccepted}
     * @memberof PhoneNumberChangeResponse
     */
    status: StatusAccepted;
    /**
     * 
     * @type {Array<PhoneNumber>}
     * @memberof PhoneNumberChangeResponse
     */
    data: Array<PhoneNumber>;
}



/**
 * Check if a given object implements the PhoneNumberChangeResponse interface.
 */
export function instanceOfPhoneNumberChangeResponse(value: object): value is PhoneNumberChangeResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PhoneNumberChangeResponseFromJSON(json: any): PhoneNumberChangeResponse {
    return PhoneNumberChangeResponseFromJSONTyped(json, false);
}

export function PhoneNumberChangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneNumberChangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusAcceptedFromJSON(json['status']),
        'data': ((json['data'] as Array<any>).map(PhoneNumberFromJSON)),
    };
}

export function PhoneNumberChangeResponseToJSON(json: any): PhoneNumberChangeResponse {
    return PhoneNumberChangeResponseToJSONTyped(json, false);
}

export function PhoneNumberChangeResponseToJSONTyped(value?: PhoneNumberChangeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusAcceptedToJSON(value['status']),
        'data': ((value['data'] as Array<any>).map(PhoneNumberToJSON)),
    };
}

