/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhoneNumber } from './PhoneNumber';
import {
    PhoneNumberFromJSON,
    PhoneNumberFromJSONTyped,
    PhoneNumberToJSON,
    PhoneNumberToJSONTyped,
} from './PhoneNumber';
import type { StatusOK } from './StatusOK';
import {
    StatusOKFromJSON,
    StatusOKFromJSONTyped,
    StatusOKToJSON,
    StatusOKToJSONTyped,
} from './StatusOK';

/**
 * 
 * @export
 * @interface PhoneNumbersResponse
 */
export interface PhoneNumbersResponse {
    /**
     * 
     * @type {StatusOK}
     * @memberof PhoneNumbersResponse
     */
    status: StatusOK;
    /**
     * 
     * @type {Array<PhoneNumber>}
     * @memberof PhoneNumbersResponse
     */
    data: Array<PhoneNumber>;
}



/**
 * Check if a given object implements the PhoneNumbersResponse interface.
 */
export function instanceOfPhoneNumbersResponse(value: object): value is PhoneNumbersResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PhoneNumbersResponseFromJSON(json: any): PhoneNumbersResponse {
    return PhoneNumbersResponseFromJSONTyped(json, false);
}

export function PhoneNumbersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneNumbersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': StatusOKFromJSON(json['status']),
        'data': ((json['data'] as Array<any>).map(PhoneNumberFromJSON)),
    };
}

export function PhoneNumbersResponseToJSON(json: any): PhoneNumbersResponse {
    return PhoneNumbersResponseToJSONTyped(json, false);
}

export function PhoneNumbersResponseToJSONTyped(value?: PhoneNumbersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusOKToJSON(value['status']),
        'data': ((value['data'] as Array<any>).map(PhoneNumberToJSON)),
    };
}

