/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderSignup
 */
export interface ProviderSignup {
    /**
     * The email address.
     * 
     * @type {string}
     * @memberof ProviderSignup
     */
    email?: string;
    /**
     * The phone number.
     * 
     * @type {string}
     * @memberof ProviderSignup
     */
    phone?: string;
    /**
     * The username.
     * 
     * @type {string}
     * @memberof ProviderSignup
     */
    username?: string;
}

/**
 * Check if a given object implements the ProviderSignup interface.
 */
export function instanceOfProviderSignup(value: object): value is ProviderSignup {
    return true;
}

export function ProviderSignupFromJSON(json: any): ProviderSignup {
    return ProviderSignupFromJSONTyped(json, false);
}

export function ProviderSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderSignup {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ProviderSignupToJSON(json: any): ProviderSignup {
    return ProviderSignupToJSONTyped(json, false);
}

export function ProviderSignupToJSONTyped(value?: ProviderSignup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phone': value['phone'],
        'username': value['username'],
    };
}

