/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestLoginCodePhone
 */
export interface RequestLoginCodePhone {
    /**
     * The phone number.
     * 
     * @type {string}
     * @memberof RequestLoginCodePhone
     */
    phone: string;
}

/**
 * Check if a given object implements the RequestLoginCodePhone interface.
 */
export function instanceOfRequestLoginCodePhone(value: object): value is RequestLoginCodePhone {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function RequestLoginCodePhoneFromJSON(json: any): RequestLoginCodePhone {
    return RequestLoginCodePhoneFromJSONTyped(json, false);
}

export function RequestLoginCodePhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestLoginCodePhone {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function RequestLoginCodePhoneToJSON(json: any): RequestLoginCodePhone {
    return RequestLoginCodePhoneToJSONTyped(json, false);
}

export function RequestLoginCodePhoneToJSONTyped(value?: RequestLoginCodePhone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

