/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestLoginCodeEmail
 */
export interface RequestLoginCodeEmail {
    /**
     * The email address.
     * 
     * @type {string}
     * @memberof RequestLoginCodeEmail
     */
    email: string;
}

/**
 * Check if a given object implements the RequestLoginCodeEmail interface.
 */
export function instanceOfRequestLoginCodeEmail(value: object): value is RequestLoginCodeEmail {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RequestLoginCodeEmailFromJSON(json: any): RequestLoginCodeEmail {
    return RequestLoginCodeEmailFromJSONTyped(json, false);
}

export function RequestLoginCodeEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestLoginCodeEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RequestLoginCodeEmailToJSON(json: any): RequestLoginCodeEmail {
    return RequestLoginCodeEmailToJSONTyped(json, false);
}

export function RequestLoginCodeEmailToJSONTyped(value?: RequestLoginCodeEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

