/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StatusAccepted = {
    NUMBER_202: 202
} as const;
export type StatusAccepted = typeof StatusAccepted[keyof typeof StatusAccepted];


export function instanceOfStatusAccepted(value: any): boolean {
    for (const key in StatusAccepted) {
        if (Object.prototype.hasOwnProperty.call(StatusAccepted, key)) {
            if (StatusAccepted[key as keyof typeof StatusAccepted] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusAcceptedFromJSON(json: any): StatusAccepted {
    return StatusAcceptedFromJSONTyped(json, false);
}

export function StatusAcceptedFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusAccepted {
    return json as StatusAccepted;
}

export function StatusAcceptedToJSON(value?: StatusAccepted | null): any {
    return value as any;
}

export function StatusAcceptedToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusAccepted {
    return value as StatusAccepted;
}

