/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyPhone
 */
export interface VerifyPhone {
    /**
     * The phone verification code
     * @type {string}
     * @memberof VerifyPhone
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyPhone interface.
 */
export function instanceOfVerifyPhone(value: object): value is VerifyPhone {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyPhoneFromJSON(json: any): VerifyPhone {
    return VerifyPhoneFromJSONTyped(json, false);
}

export function VerifyPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyPhone {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function VerifyPhoneToJSON(json: any): VerifyPhone {
    return VerifyPhoneToJSONTyped(json, false);
}

export function VerifyPhoneToJSONTyped(value?: VerifyPhone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

