/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebAuthnCredentialCreationOptions
 */
export interface WebAuthnCredentialCreationOptions {
    /**
     * 
     * @type {object}
     * @memberof WebAuthnCredentialCreationOptions
     */
    creationOptions: object;
}

/**
 * Check if a given object implements the WebAuthnCredentialCreationOptions interface.
 */
export function instanceOfWebAuthnCredentialCreationOptions(value: object): value is WebAuthnCredentialCreationOptions {
    if (!('creationOptions' in value) || value['creationOptions'] === undefined) return false;
    return true;
}

export function WebAuthnCredentialCreationOptionsFromJSON(json: any): WebAuthnCredentialCreationOptions {
    return WebAuthnCredentialCreationOptionsFromJSONTyped(json, false);
}

export function WebAuthnCredentialCreationOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnCredentialCreationOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'creationOptions': json['creation_options'],
    };
}

export function WebAuthnCredentialCreationOptionsToJSON(json: any): WebAuthnCredentialCreationOptions {
    return WebAuthnCredentialCreationOptionsToJSONTyped(json, false);
}

export function WebAuthnCredentialCreationOptionsToJSONTyped(value?: WebAuthnCredentialCreationOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creation_options': value['creationOptions'],
    };
}

