/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebAuthnCredentialRequestOptions
 */
export interface WebAuthnCredentialRequestOptions {
    /**
     * 
     * @type {object}
     * @memberof WebAuthnCredentialRequestOptions
     */
    _requestOptions: object;
}

/**
 * Check if a given object implements the WebAuthnCredentialRequestOptions interface.
 */
export function instanceOfWebAuthnCredentialRequestOptions(value: object): value is WebAuthnCredentialRequestOptions {
    if (!('_requestOptions' in value) || value['_requestOptions'] === undefined) return false;
    return true;
}

export function WebAuthnCredentialRequestOptionsFromJSON(json: any): WebAuthnCredentialRequestOptions {
    return WebAuthnCredentialRequestOptionsFromJSONTyped(json, false);
}

export function WebAuthnCredentialRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnCredentialRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
        '_requestOptions': json['request_options'],
    };
}

export function WebAuthnCredentialRequestOptionsToJSON(json: any): WebAuthnCredentialRequestOptions {
    return WebAuthnCredentialRequestOptionsToJSONTyped(json, false);
}

export function WebAuthnCredentialRequestOptionsToJSONTyped(value?: WebAuthnCredentialRequestOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_options': value['_requestOptions'],
    };
}

