/* tslint:disable */
/* eslint-disable */
/**
 * django-allauth: Headless API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: info@allauth.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebAuthnAuthenticator
 */
export interface WebAuthnAuthenticator {
    /**
     * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
     * 
     * @type {number}
     * @memberof WebAuthnAuthenticator
     */
    lastUsedAt: number;
    /**
     * An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
     * 
     * @type {number}
     * @memberof WebAuthnAuthenticator
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnAuthenticator
     */
    type: WebAuthnAuthenticatorTypeEnum;
    /**
     * Authenticator ID.
     * 
     * @type {number}
     * @memberof WebAuthnAuthenticator
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnAuthenticator
     */
    name: string;
    /**
     * Whether or not this authenticator represents a passkey. Absent if it is not specified.
     * 
     * @type {boolean}
     * @memberof WebAuthnAuthenticator
     */
    isPasswordless?: boolean;
}


/**
 * @export
 */
export const WebAuthnAuthenticatorTypeEnum = {
    Webauthn: 'webauthn'
} as const;
export type WebAuthnAuthenticatorTypeEnum = typeof WebAuthnAuthenticatorTypeEnum[keyof typeof WebAuthnAuthenticatorTypeEnum];


/**
 * Check if a given object implements the WebAuthnAuthenticator interface.
 */
export function instanceOfWebAuthnAuthenticator(value: object): value is WebAuthnAuthenticator {
    if (!('lastUsedAt' in value) || value['lastUsedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WebAuthnAuthenticatorFromJSON(json: any): WebAuthnAuthenticator {
    return WebAuthnAuthenticatorFromJSONTyped(json, false);
}

export function WebAuthnAuthenticatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnAuthenticator {
    if (json == null) {
        return json;
    }
    return {
        
        'lastUsedAt': json['last_used_at'],
        'createdAt': json['created_at'],
        'type': json['type'],
        'id': json['id'],
        'name': json['name'],
        'isPasswordless': json['is_passwordless'] == null ? undefined : json['is_passwordless'],
    };
}

export function WebAuthnAuthenticatorToJSON(json: any): WebAuthnAuthenticator {
    return WebAuthnAuthenticatorToJSONTyped(json, false);
}

export function WebAuthnAuthenticatorToJSONTyped(value?: WebAuthnAuthenticator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_used_at': value['lastUsedAt'],
        'created_at': value['createdAt'],
        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'is_passwordless': value['isPasswordless'],
    };
}

